apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
    # Inside the cluster, what port does the service expose?
  - port: 31001
    # Which port on the node is the service available through?
    nodePort: 31001
    # Which port do pods selected by this service expose?
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
